### ISSUE TITLE
Preview for site - Netlify?

### ISSUE THREAD

**Issue by vsoch** [hpc-social/hpc-social.github.io#1]
@alansill I'm a huge fan of Netlify for previewing sites - I have my own free account but I wonder if HPC social could have it's own free account? https://www.netlify.com/pricing/ The interactions with GitHub issues / PRs are seriously beautiful - I tested on US-RSE but couldn't keep it because our build frequency (e.g., common updates to jobs) would go over the free tier.

Here is an example build (from a while ago) to show how it works: https://github.com/USRSE/usrse.github.io/pull/774#issuecomment-1085211932

I'll prepare a config to anticipate using it, but if we cannot we can fall back to CircleCI (not the best user experience but gets the job done!)

**Comment by alansill** [comment]
Hmm, I signed up but the team seems to be limited to me and adding members would cost $. How can we link it to a GitHub organization and avoid membership limitations?

**Comment by vsoch** [comment]
Done! https://mastodon.social/@vsoch/109401606084681488
