### ISSUE TITLE
Links for hpc.social server policies

### ISSUE THREAD

**Issue by alansill** [hpc-social/hpc-social.github.io#15]
I have created a page for site policies in the hpc-social/mastodon-policies repository. Is there an easy way to transfer these pages into the main web site or should I make a new policies.hpc.social web destination for them? Incorporating them seems better.

**Comment by vsoch** [comment]
I'll make a policy page over thanksgiving!

**Comment by alansill** [comment]
Thanks. We're using the Mastodon default privacy policy that gets pulled in if you don't supply another, as it looked okay to me. I made a new DMCA page after extensive review of the one suggested online by Dreamwidth and conversion to Markdown for easier maintenance. You may have to rearrange these to fit the main server pattern as I didn't want to mess with the site layout and this did not seem to be a suitable topic for a project. Making it clear that people can suggest revisions via GitHub from this repository or wherever you may move these files to would be helpful. Other suggestions welcome. Thanks!

**Comment by alansill** [comment]
I think we have this covered now with the new additions to the "About" page of the Mastodon instance and so probably don't need an explicit link to there on the main web site. You might consider making a link to the "Discussion" area of the hpc-social.github.io repository from the main web site, but I'll add that as another issue and close this one for now. Thanks!

**Comment by vsoch** [comment]
@alansill do the policies extend to the community though? I think a page would still be worth it, even if linked in small text at the bottom. I know how to render a markdown from a repository into a web UI so the implementation shouldn't be hard (or hard to keep up to date, in fact it will always be!)

**Comment by alansill** [comment]
Cook's choice, I think. Linked in small text at the bottom would be good. I considered making it a page on the site or its own site but I think it works as a repository because that makes it explicit that the policies are open to input from the community. Can you make a link that renders just the Readme.md file somewhere on the site, or perhaps add a website policies link to that page of the repository customized to the web site features? For this task up to now Ive tried to concentrate on the Mastodon-specific aspects including some concerns that I saw raised in posts on Twitter and Mastodon in the community at large. I'm happy with whatever you decide. (See [other issue](https://github.com/hpc-social/hpc-social.github.io/issues/20).)

**Comment by vsoch** [comment]
Okay - will figure something out!

I'm finishing up some NextFlow and weird spack build stuff, should be able to work on this next.

**Comment by vsoch** [comment]
okay looking closer - these _are_ specific to Mastodon, so I'm going to put them on the Mastodon project page. Yell at me if this isn't a good idea, or you want to discuss elsewhere!
