### ISSUE TITLE
Suggestion - organization might be instead hpc-social?

### ISSUE THREAD

**Issue by vsoch** [hpc-social/hpc-social.github.io#2]
@alansill I noticed just now that you named the org to HPC-social - and this should still be found by typing in github.com/hpc-social - I want to suggest (and feel free to disregard) to use all lowercase. I think it mostly just looks better. E.g.,:

![image](https://user-images.githubusercontent.com/814322/202923908-1a55e838-82fa-4e0b-8388-af9a2bb0fb7c.png)

vs. 

![image](https://user-images.githubusercontent.com/814322/202923925-afd7ab01-521f-4d63-b080-72e667f4dbc6.png)

It's a subtle difference, but (to me) having caps is (for the most part) an indicator of an old school project or org. It just doesn't make sense to add complexity of making someone guess capitalization. And then when you are having conversations with people or similar, you don't always have to add the caveat "Oh the HPC is capitalized." 

Feel free to close if you are wed to the capital letters - but wanted to speak up earlier than later.

**Comment by alansill** [comment]
I renamed it and https://github.com/hpc-social seems to work but the change to case does nto seem to have propagated yet to the repository listing view. Maybe an eventual consistency thing?

**Comment by vsoch** [comment]
It's likely just cached - if you open devtools it shouldn't use the cache! Looks good to me!

![image](https://user-images.githubusercontent.com/814322/202925053-94a92312-8cc3-4de1-987c-96a22508ddf5.png)

Thank you!

**Comment by vsoch** [comment]
Actually this page isn't lowercase yet for me - I'm going to leave this open (and check in a few hours) and then I'll close when it's hopefully updated.

**Comment by vsoch** [comment]
Done!
