### ISSUE TITLE
Consider link on web site to GitHub Discussions area

### ISSUE THREAD

**Issue by alansill** [hpc-social/hpc-social.github.io#20]
Consider making a link to the "Discussion" area of the hpc-social.github.io repository from the main web site (https://github.com/hpc-social/hpc-social.github.io/discussions) to provide an avenue for suggesting ideas for improvements to the site.

**Comment by vsoch** [comment]
@alansill I think we need a more broad "contact" page - can you give me a list of "all the places" that someone could get in contact / ask a question / etc? Akin to the mastodon-policies repository, but just with the contact info,. Then I'll make us a contact page proper.

**Comment by alansill** [comment]
The "About" page at [https://mast.hpc.social/about](https://mast.hpc.social/about) and the [Profiles Directory](https://mast.hpc.social/directory) are good things to link.

**Comment by alansill** [comment]
I'll work on a list but the basic ones are in the links above.

**Comment by vsoch** [comment]
I think these are community links so I'm going to start by putting them on the front page. If we ever need a private way for people to contract, I think the HPC.social admin emails are best, but I'll link to an example form https://shawnyeager.com/contact/ in case we need something different.

**Comment by alansill** [comment]
This is good for now. If needed we can open another issue for the contact form.
