### ISSUE TITLE
Add Mastodon server user account badge

### ISSUE THREAD

**Issue by alansill** [hpc-social/hpc-social.github.io#21]
The following link will generate an image showing the current mast.hpc.social total accounts that could be put at some appropriate place on the web site:

https://img.shields.io/badge/dynamic/json?label=Accounts&query=stats.user_count&url=https%3A%2F%2Fmast.hpc.social%2Fapi%2Fv1%2Finstance

You can try it out in your browser to see what it would look like. The idea would be to embed this badge somewhere useful on the hpc.social web site.

**Comment by vsoch** [comment]
yeah that looks spiffy! 
![image](https://user-images.githubusercontent.com/814322/203866783-4b441519-8140-4a4e-8b50-8d17369ed352.png)
