### ISSUE TITLE
Links need to be checked/sanitized before posting

### ISSUE THREAD

**Issue by alansill** [hpc-social/hpc-social.github.io#28]
Allowing entry of arbitrary urls and text for the map opens the door to spammers using the entry fields for malicious or unsafe content. We should implement a way to check these either manually or through some sort of online sanitizing/checking service as used in Microsoft Safe Links before posting them to the map.

**Comment by vsoch** [comment]
If you have an idea for a service, it should be fairly easy to add to the automation! Are we getting spammed already?

**Comment by vsoch** [comment]
We can also fall back to the manual checking strategy - e.g., run once a month, where it opens a PR and someone checks. That's more manual work though, not ideal. Or add some kind of verification on the front end, or require email ?

**Comment by alansill** [comment]
Not yet but it’s likely that we will at some point. OGF SourceForge (GridForge) and Redmine comment forums got spammed regularly and those required an account signup.

The Mastodon service has reporting and blocking features and now we have 5 moderators signed up to check for moderation requests with their own email list for reporting and email communication among that group. We *might* be able to talk them into reviewing the entries in the map links and labels periodically if we make the output of the form available to them. If it’s stored on the hpc.social google drive you could consider sharing that with the ***@***.*** group with a request to look it over at intervals (not sure of the best interval or review method).

I don’t know of an automated service offhand so that would take some research. Even the text fields are somewhat of a risk. Are these inputs sanitized and/or protected from potential malicious input, or doer the Google Forms input protect us from script kiddie manipulation attempts for example?

On Nov 25, 2022, at 12:43 AM, Vanessasaurus ***@***.***> wrote:

﻿
This email originated outside TTU. Please exercise caution<https://askit.ttu.edu/phishing>!


If you have an idea for a service, it should be fairly easy to add to the automation! Are we getting spammed already?

**Comment by vsoch** [comment]
It's being POSTed to the Google form, so whatever protections they have are inherited I suspect. I'll have to think about ways to check too. At least when I was managing the US-RSE map, I would manually check every entry, but only do that (and the update) once a month.

**Comment by vsoch** [comment]
Are you worried about bots or malicious humans?

**Comment by vsoch** [comment]
Here is one - https://medium.com/artificialis/phishing-url-detection-with-python-a2c3dd3a87e8 looks like the API allows 5K free per month. Should we try it? I can keep a cache of known URLs so we don't check any twice, and fail the action if one is detected.

**Comment by alansill** [comment]
Looks useful. Shall we try it? Also need to worry about XSS and other injection attacks, especially if youʻre storing inputs in a database. Also we should be careful of any add-ons: https://deepai.org/publication/xss-vulnerabilities-in-cloud-application-add-ons

Drupal seems to follow the mantra of "sanitize on output not input" but I am not certain of the best approach.  https://www.drupal.org/docs/security-in-drupal/writing-secure-code-for-drupal

Might cut down the problem by using a captcha but that would have to be done outside of the form itself. Here are some input regex methods: https://www.labnol.org/internet/regular-expressions-forms/28380/ and hereʻs a more advanced approach but it requires (you guessed it) an add-on: https://xfanatical.com/blog/captcha-for-forms/

**Comment by vsoch** [comment]
@alansill but it’s already going to a Google form - do Google forms not have some of these checks already? If you shared a google form online would you add all these same checks?  🤔

**Comment by alansill** [comment]
Right; the links above are intended to increase the security of the form and keep bots and other malicious entries in check,

**Comment by alansill** [comment]
Maybe add an email address to the form for a verification confirmation (send an email with a confirmation link to confirm before posting the link or entry)? This could get elaborate I suppose but might help. I'll make a separate issue for this on the map repository.

**Comment by alansill** [comment]
Closing this for now as the current method seems to be working, but feel free to reopen it or to put in related issues such as perhaps calling for volunteers to help check the input and review!
