### ISSUE TITLE
Image preview missing from social media posts

### ISSUE THREAD

**Issue by alansill** [hpc-social/hpc-social.github.io#29]
Posting the link to hpc.social does not yield an image preview in the card/attachment rendered by Twitter or Mastodon.
![Screen Shot 2022-11-25 at 1 17 57 PM](https://user-images.githubusercontent.com/2364484/204044144-d76fb73b-5764-4f13-bfef-22f99e04830e.png)

**Comment by vsoch** [comment]
This is a repeat of #9 - I can work on this now.
