### ISSUE TITLE
Links on home page with other social media icons for Mastodon

### ISSUE THREAD

**Issue by alansill** [hpc-social/hpc-social.github.io#33]
I've gotten a complaint that someone went to the hpc.social site and didn't see "where to sign up". Should we put a link on home page with other social media icons for Mastodon site? The downside of this is that the other links are to individual administrative contact accounts, so it would be inconsistent to have a Mastodon icon that takes you to the site instead of to the admin contact. Still it would be better than nothing.

Perhaps we could add such an icon -- I looked but didn't see where the three that are there already are selected, though I did find a page of info for a bunch of social media providers that unfortunately did not list Mastodon, so haven't taken any action on this. 

If we wanted to be consistent we could add an iconized link like the others that send you to the [https://mast.hpc.social/@admin](https://mast.hpc.social/@admin) account page but put a text link to the Mastodon site About page, which includes links to sign in or create an account when not signed in already, with a label like [Join us on Mastodon](https://mast.hpc.social/about) for that link.

**Comment by alansill** [comment]
I think I see that we are getting the other icons bu selecting them in https://github.com/hpc-social/hpc-social.github.io/blob/main/_data/social.yml from the icomoon portion of the repository at https://github.com/hpc-social/hpc-social.github.io/tree/main/assets/icomoon/fonts and they have not added one for Mastodon yet. See https://github.com/Keyamoon/IcoMoon-Free/issues/25

Is there a way to wok around this to achieve the above?

**Comment by alansill** [comment]
Ah, if you go to the IcoMoon site you can search for "mastodon" and it is available in the "brands" package and can apparently generate a font online for that for free. Here's a link taht will be good for 24 hours, or you can go there and make one of your own: https://i.icomoon.io/public/reference.html#/temp/01853af216/UntitledProject/

**Comment by alansill** [comment]
Hmm, is it just a matter of adding in a reference to font code E900 from the Brands font set? How is the list in https://github.com/hpc-social/hpc-social.github.io/blob/main/_data/social.yml generated?

**Comment by alansill** [comment]
While we figure out the icon for a link to the @admin@mast.hpc.social contact account, I added the "Join Us On Mastodon" link to the menu via https://github.com/hpc-social/hpc-social.github.io/pull/35. Please check.

**Comment by vsoch** [comment]
How is a link without words to the mastodon instance the same clarity as "Join us on Mastodon" but "Join Mastodon" is not? :thinking:  Usually these icons indicate personal social media accounts and don't imply "click here to join." The solution isn't an icon (although we can add one) but rather there needs to be an obvious Join button, something like on the us-rse site 

![image](https://user-images.githubusercontent.com/814322/204063559-1f04c9ee-df75-47ed-96c9-5c7faf21e333.png)

**Comment by vsoch** [comment]
My suggestion for a "quick fix" is to put just "Mastodon" on the home page, and have that link to the Mastodon project page, and then add a large obvious button that says "Join" there. I think that will be easy to find, and then obvious that clicking == Join.

**Comment by alansill** [comment]
The other icons take you to an account, not the instance (for example, the Twitter icon takes you to the hpc_social account on Twitter not to twitter.com). I think it would be consistent to add a Mastodon icon if we can figure out the isomoon font stuff that links to the https://mast.HPC.social/@admin account and use the text link to provide the link to join. I agree that linking to the server itself through the icon would not help because some people may not even know what the Mastodon icon looks like so it's better to use it for something like linking to the contact account.

Thanks for working to help get these details right! I don't mind at all having or hearing different views as they help work out these important issues.

**Comment by vsoch** [comment]
I really don't like to do things rushed, it's stressful and I prefer to get things figured out and do them right. This interaction was particularly stressful for me.

**Comment by alansill** [comment]
Apologies.

**Comment by vsoch** [comment]
No worries! I know I'm a different phenotype than most. I did a lot of work today (and in the last week) and I'm going to step away from working on this for a bit so I can work on other things. I'll be back after that!
