### ISSUE TITLE
add DNS then CNAME

### ISSUE THREAD

**Issue by vsoch** [hpc-social/hpc-social.github.io#4]
@alansill we will want to follow instruction https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site and add a CNAME to the repository (once you configure DNS if you want to just tell me I'm happy to add the file). Importantly, please let's do https://hpc.social as the default - it's OK if https://www.hpc.social works, but it's longer to type (and I think?) looks cooler without the www. Also, some browsers have toyed with "doing away with" the www, so it's safer to not make that the only registered pattern (fine to support it though!)

**Comment by alansill** [comment]
Sure, I've done this many times. Assume the hpc-social.github.io repository is intended as the main site?

**Comment by vsoch** [comment]
Yes! The way GitHub pages works is that a repository named `<username>.github.io` renders to that web URL. If we add the CNAME here, all other repos that deploy to GitHub pages will also take on that prefix (e.g., `https://hpc-social.github.io/map` --> `https://hpc.social/map`. You will want to make sure to configure the DNS so it's using the name and not something like a redirect, etc.

**Comment by alansill** [comment]
Just waiting on DNS now

**Comment by vsoch** [comment]
Go DNS go! I think we will need to do this https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages and then add the hpc.social to settings here, and the CNAME file (at least from the last time I did it).

I just got the cool map submit form working - https://hpc-social.github.io/projects/map/ give it a shot and see if it works for you! As long as I get a full name city/state/country (or city/country) I should be able to geolocate. I figured out how to get the form embedded in the site to submit to Google forms - it actually is just a slightly modified forms URL to post to, and then you have to get the names of the form fields to match.

**Comment by alansill** [comment]
Don't understand why but I'm still getting "You must verify your domain hpc.social before being able to use it. Check out https://docs.github.com/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages for more information." -- even thought the [domains](https://github.com/organizations/hpc-social/settings/domains) page says "verified" for both the bare domain and the www subdomain. I've done this *many* times for other repositories and never had a problem or a delay this long. Will check again tomorrow.

**Comment by vsoch** [comment]
Is there perhaps a permission missing? I don't see any under the org settings -> Pages --> Verified domains

![image](https://user-images.githubusercontent.com/814322/202961596-0a582a79-4ce0-4f2f-890e-9c8b2d523c13.png)

**Comment by vsoch** [comment]
@alansill try this link - this is under pages https://github.com/organizations/hpc-social/settings/pages

**Comment by vsoch** [comment]
I think the difference is that you can have domains on the level of the org (used for notifications, etc. not necessarily pages) and th ones under CNAME are a different think. The two places that essentially look the same indeed isn't great!

**Comment by alansill** [comment]
![Screen Shot 2022-11-20 at 10 07 25 PM](https://user-images.githubusercontent.com/2364484/202963640-ee36d3fe-c53c-4ee2-8b5a-3d66a30091d9.png)

**Comment by vsoch** [comment]
@alansill I can see your URL is different than the one I posted - mine ends in pages. I can see that URL too and it looks good but it’s a different page.

**Comment by alansill** [comment]
Okay, using the [pages link](https://github.com/organizations/hpc-social/settings/pages) instead of the overall org link for verification worked. Certs being provisioned now, should be available at the https://hpc.social link shortly.

**Comment by vsoch** [comment]
Woot!

**Comment by alansill** [comment]
Closed as resolved.
