### ISSUE TITLE
Add Developer Stories as Project?

### ISSUE THREAD

**Issue by vsoch** [hpc-social/hpc-social.github.io#40]
@alansill can we add the [Developer Stories](https://rseng.github.io/devstories/) podcast as a Project? I have featured many HPC community members and projects, and I think it could serve as a good voice for the community. If someone comes to the hpc.social site and wants to be interviewed, I'd love to have them! And also if you think / know of someone that would be a good guest, I can reach out to them too.

**Comment by alansill** [comment]
Oh, sure, that would be great! Should we label it explicitly as a joint project with US-RSE, or as a project of that organization that we are highlighting for community participation and/or breadth of coverage? Any of thee would be okayu with me. (I want to get the context of this right, but it is *absolutely* in context that we want to promote communication between and among developers and maintainers of software and their researcher communities!) 

Should the project be "Developer Communications" with "Developer Stories" as one sub-project or page/collection? What are the possibilities here?

**Comment by vsoch** [comment]
When it was called RSE Stories, it was never a "US-RSE" project, it was entirely imagined and produced by me. This year I had to step away from that community https://vsoch.github.io/2022/code-of-conduct/ so the association is broken. I've continued the podcast as the more inclusive "Developer Stories." US-RSE has no ownership or name to it.

**Comment by vsoch** [comment]
And I think (for now) while we have a tiny number of projects, giving it it's own page makes most sense. if a second podcast comes along, we could have one top level entry for "Podcasts" but even then I think each should get it's own page. There is no upper limit to the number of projects we can have!

**Comment by vsoch** [comment]
But actually, do you know of other HPC community podcasts? If there are a few, then a "Podcasts" project page could be cool, highlighting that they are maintained by community members (and people are welcome to be on the shows if relevant!)

**Comment by vsoch** [comment]
Okay so updated proposal: how about we add a "Podcasts" project page, under which we can list as many as we like?

**Comment by alansill** [comment]
Ah, I remember some of those posts and now see the larger story. FYI, we've already had our first two reports on posts from an account on the mast.hpc.social server. 

As it happens I had already set up an email group for the five people plus me who have volunteered to be mast.hpc.social moderators, which is consistent with your recommendations, and used that to discuss the reports. They were for three posts from a newly created account that is almost all HPC hardware oriented who had engaged with a post claiming marginalization experiences in Mastodon in general for members of the black community. I can send you those posts if you are interested, and separately can add you to the moderators group if you are interested (warning: this will result in traffic from the server as it wants to be baby-sat every day n terms of allowed trending hashtags and posts). And in place of a code of conduct, which was popular but not uniformly supported among respondents to the initial survey, I have decided for now to stick with the terms of service from our upstream provider, which are pretty good, coupled with the privacy statement and the DMCA provisions. So I hope that will be enough for now. (FYI, the posts were removed when we sent information to the person who posted them gently asking for additional attention.)

Back to the original subject: I agree this would be a nice addition to the site. I am also trying to think about how to achieve more goals pointed to in the survey, like avenues to get information about new hardware and software options and their use. 

"HPC Podcasts" perhaps? Yes, I like listing multiple and asking people if they have blogs or podcasts to promote.

**Comment by vsoch** [comment]
Blogs would be a good idea, but if we go that direction I think it should be a separate project type from podcasts - they are very different! We could also do a community syndicated blog as I did for us-rse: https://us-rse.org/blog/

How about just "Podcasts?" It's under the hpc.social site so we know that HPC is relevant. And the podcasts don't necessarily have to only be HPC specific, that's a bit limiting (mine is not!)

**Comment by alansill** [comment]
Let's do it and see if there is any feedback one way or the other. Maybe make it clear that we are happy to add others.
