### ISSUE TITLE
Add our podcast?

### ISSUE THREAD

**Issue by swebb-krell** [hpc-social/hpc-social.github.io#49]
Hi-- I'm Sarah Webb at the Krell Institute. We just joined the community as @sciencemachines. 

Would you please consider adding our podcast, [Science in Parallel](http://scienceinparallel.org)? Thank you!

**Comment by vsoch** [comment]
Absolutely! Will do later today and update you here when I do.

**Comment by vsoch** [comment]
hey @swebb-krell ! I'm not able to see the page because it doesn't have https - 
![image](https://user-images.githubusercontent.com/814322/204596131-926f3152-b286-46ec-b3c0-03a4181e2c5f.png)

Is there any chance you could add it? Do you need any help?

**Comment by vsoch** [comment]
Another strategy is to share it via another site - here are some quick ones I found!

- https://www.krellinst.org/csgf/outreach/science-in-parallel
- https://podcasts.apple.com/us/podcast/science-in-parallel/id1577369236

**Comment by vsoch** [comment]
Please see https://github.com/hpc-social/hpc-social.github.io/pull/50! Netlify will generate  a preview link that you can check out - if there are notable episodes (or other text) you want to add, please let me know.
