### ISSUE TITLE
404 on news landing page link

### ISSUE THREAD

**Issue by FCLC** [hpc-social/hpc-social.github.io#5]
On landing page: https://hpc-social.github.io/ 

Under Community/News, clicking/taping news, the URL is currently: https://hpc-social.github.io/new/, causing a 404. 

I believe this is meant to be https://hpc-social.github.io/news/ ?

**Comment by vsoch** [comment]
haha, indeed! I'll fix that right up!

**Comment by vsoch** [comment]
Wait can you show me more specifically? I don't see where it has "new" - the landing page "news" I am taken to:

![image](https://user-images.githubusercontent.com/814322/202938830-8787ec0a-45e2-40db-84e7-a64e058edad3.png)

Am I looking in the wrong spot?

**Comment by FCLC** [comment]
<img width="554" alt="Screen Shot 2022-11-20 at 8 20 28 PM" src="https://user-images.githubusercontent.com/20584423/202938926-3c8c1897-3822-4fe8-b6d1-24f2dfb0357c.png">
