### ISSUE TITLE
Site navigation issues

### ISSUE THREAD

**Issue by alansill** [hpc-social/hpc-social.github.io#56]
I'm getting a "Coming Soon" message when navigating on mobile to the web site home page. Also, when browsing to the Projects page on a limited cellular network, not all of the content seems to load. Not sure what is happening here. ![image](https://user-images.githubusercontent.com/2364484/210156915-7daeb04e-a562-422d-a77e-8acdc21650e3.png)

**Comment by vsoch** [comment]
That's the main page: 
![image](https://user-images.githubusercontent.com/814322/210156988-f9616eb5-36ec-4877-af0b-350db07be159.png)


The difference is that on mobile it's a scroll down, in the web UI you click the dinosaur to see it.

**Comment by alansill** [comment]
Ah, I see. It's just more obvious in the mobile presentation because the primary interaction there is to scroll. (I rarely scroll on the desktop site so things that require scrolling there are less obvious.)

So is this vestigial or are there resources we can add? Need any help or suggestions here?

**Comment by vsoch** [comment]
I'm down with whatever you'd like to add! This is just the index.md file so if you want to do a PR with some content I'm happy to review!
