### ISSUE TITLE
Add Scigeeks' podcast

### ISSUE THREAD

**Issue by dciangot** [hpc-social/hpc-social.github.io#78]
This is to ask for the inclusion of the podcasts list of the "Scigeeks' Podcast" here (as per mastodon invite by @alansill ):

https://www.youtube.com/playlist?list=PLnm27H265Le6wyly4tofH8_Mb4fg-bW8X

The topics are usually around the computing for science with an alternating of startup/industry vision and scientific domain investigations.

**Comment by vsoch** [comment]
This would be great! You can open a PR and add it to this page:

https://github.com/hpc-social/hpc-social.github.io/blob/main/_projects/podcasts.md

**Comment by dciangot** [comment]
done in #79 !

**Comment by vsoch** [comment]
Closed with #79
